#!/bin/bash

JS_SCRIPT="teamA.js"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 0; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 1; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 2; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 3; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 4; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 5; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 6; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 7; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 8; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 9; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT 10; exec bash"

JS_SCRIPT2="teamB.js"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 0; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 1; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 2; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 3; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 4; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 5; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 6; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 7; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 8; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 9; exec bash"
gnome-terminal -- bash -c "echo 'start'; node $JS_SCRIPT2 10; exec bash"
